Food Score Prediction using ML Models

In [45]:
import numpy as np
import pandas as pd
data=pd.read_csv("nutrition.csv")
data.drop('Date', axis=1, inplace=True)
data.drop('Entry', axis=1, inplace=True)
data.drop('Food', axis=1, inplace=True)
data

Meal Food Score calories (kcal)  carbs (g)  fat (g)  protein (g)  \
0     Breakfast    Healthy             105         27        0            1   
1     Breakfast    Neutral             150          8        3           25   
2     Breakfast    Neutral             183         14       10           10   
3         Lunch    Neutral             210         39        3            8   
4         Lunch    Neutral             160          1        8           22   
...         ...        ...             ...        ...      ...          ...   
1231      Lunch    Healthy             120          2       14           20   
1232     Dinner  Unhealthy           1,296        180       29           45   
1233     Snacks    Healthy             340         14       28           12   
1234     Snacks    Neutral             100         18        3            2   
1235     Snacks    Neutral             272         44        7            7   

     sodium (mg)  sugar (g)  
0              1         14  
1            100          2  
2            122         16  
3            370          1  
4             85          0  
...          ...        ...  
1231           0          0  
1232       2,187          0  
1233           0          0  
1234          15          8  
1235         543          2  

[1236 rows x 8 columns]

DATA PREPROCESSING

In [46]:
from sklearn.preprocessing import StandardScaler
data=data.dropna()
scaler = StandardScaler()
from sklearn.preprocessing import LabelEncoder
# create a label encoder object
le = LabelEncoder()
# fit and transform the categorical column
data['calories (kcal)'] = data['calories (kcal)'].str.replace(',', '')
data['sodium (mg)'] = data['sodium (mg)'].str.replace(',', '')
data['Meal'] = le.fit_transform(data['Meal'])
data['Food Score'] = le.fit_transform(data['Food Score'])
print(data)
X=data.drop('Food Score',axis=1)
print(X)

      Meal  Food Score calories (kcal)  carbs (g)  fat (g)  protein (g)  \
0        0           0             105         27        0            1   
1        0           1             150          8        3           25   
2        0           1             183         14       10           10   
3        4           1             210         39        3            8   
4        4           1             160          1        8           22   
...    ...         ...             ...        ...      ...          ...   
1231     4           0             120          2       14           20   
1232     2           2            1296        180       29           45   
1233     5           0             340         14       28           12   
1234     5           1             100         18        3            2   
1235     5           1             272         44        7            7   

     sodium (mg)  sugar (g)  
0              1         14  
1            100          2  
2        

RANDOM FOREST Model to Predict Food Score

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,r2_score,mean_squared_error
data=data.dropna()
scaler = StandardScaler()

X=scaler.fit_transform(X)
y=data['Food Score']
selector=SelectKBest(k=7)
X=selector.fit_transform(X, y)
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Choose the model
model = RandomForestClassifier(n_estimators=100, max_depth=8)
# Train the model
model.fit(X_train, y_train)
# Evaluate the model
y_pred1 = model.predict(X_test)
print("Confusion matrix")
print(confusion_matrix(y_test,y_pred1))
a=accuracy_score(y_test, y_pred1)
mse = mean_squared_error(y_test, y_pred1)
r2 = r2_score(y_test, y_pred1)
print()
data={'Accuracy':[a],
      'Mean Squared Error':[mse],
      'R2 Score':[r2]}
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)

Confusion matrix
[[86  1  2]
 [ 2 63  4]
 [ 4  1 85]]

   Accuracy  Mean Squared Error  R2 Score
0  0.943548            0.129032  0.821225


MULTILAYER PERCEPTRON (FEED FORWARD NEURAL NETWORK) to Predict Food Score

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Build the MLPClassifier model
clf = MLPClassifier(hidden_layer_sizes=(100, 50), activation='relu', max_iter=500)

# Train the model
clf.fit(X_train, y_train)

# Test the model and calculate the accuracy
y_pred2 = clf.predict(X_test)
# Evaluate model performance
print("Confusion matrix")
print(confusion_matrix(y_test,y_pred2))
a=accuracy_score(y_test, y_pred2)
mse = mean_squared_error(y_test, y_pred2)
r2 = r2_score(y_test, y_pred2)
print()
data={'Accuracy':[a],
      'Mean Squared Error':[mse],
      'R2 Score':[r2]}
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)

Confusion matrix
[[87  2  0]
 [ 3 64  2]
 [ 4  2 84]]

   Accuracy  Mean Squared Error  R2 Score
0  0.947581            0.100806  0.860332


c:\Users\91965\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


XGBOOST Model to Predict Food Score

In [49]:
import xgboost as xgb
# Train an XGBoost classifier
xgb_model = xgb.XGBClassifier()
xgb_model.fit(X_train, y_train)
# Evaluate the classifier's performance on the testing set
y_pred3 = xgb_model.predict(X_test)
print("Confusion matrix")
print(confusion_matrix(y_test,y_pred3))
a=accuracy_score(y_test, y_pred3)
mse = mean_squared_error(y_test, y_pred3)
r2 = r2_score(y_test, y_pred3)
print()
data={'Accuracy':[a],
      'Mean Squared Error':[mse],
      'R2 Score':[r2]}
# Create DataFrame
df = pd.DataFrame(data)
# Print the output.
print(df)

Confusion matrix
[[89  0  0]
 [ 3 64  2]
 [ 4  0 86]]

   Accuracy  Mean Squared Error  R2 Score
0   0.96371            0.084677  0.882679
